str = "This is a string with multiple words"
print(str.capitalize())
print(str.casefold())
# print(str.center())
print(str.count("i"))
print(str.encode())
print(str.endswith("j"))
print(str.expandtabs())
print(str.find("i"))
print(str.format("i"))